### ISSUE TITLE
WOW!

### ISSUE THREAD

**Issue by seetch** [FrontierDevs/Genisys3#2]
Real? Unite, you're all done and create 1 normal core!

**Comment by RTGDaCoder** [comment]
Normal Core? Like GeniCore xD. I think we are more focused on MCPE 1.1.0 concurrently. We will think about the other later part....

**Comment by sharletsings123** [comment]
xD

**Comment by FienixEC** [comment]
so this isnt supporting 1.0.5?

**Comment by xXSirGamesXx** [comment]
It supports 1.0.5 Just download the master version.

**Comment by RTGDaCoder** [comment]
We are sure that we added MCPE 1.0.5 support

**Comment by CrusherPlaysMC** [comment]
Issue is dead. Locking....
