### ISSUE TITLE
Can't Join / Kicked by timeout

### ISSUE THREAD

**Issue by iMOEchan** [FrontierDevs/Genisys3#3]
when I tried to join into the server, it's always give message"Login Timeout"

IMG: http://i.hizliresim.com/BrajjV.jpg

**Comment by eDroiid** [comment]
hmm.. try uninstalling and re-installing mcpe.

**Comment by RTGDaCoder** [comment]
Which software are you using to run it?

**Comment by iMOEchan** [comment]
@RTGDaCoder Genisys3 :/

**Comment by iMOEchan** [comment]
@eDroiid I'll try it later

**Comment by xXSirGamesXx** [comment]
one sec. I'm fixing

**Comment by xXSirGamesXx** [comment]
Fixed this issue. re download G3 1.0.5 and it should work

**Comment by xXSirGamesXx** [comment]
nvm fixed again xD

**Comment by xXSirGamesXx** [comment]
Well there seems to be am issue with the files on GitHub. try the src.zip and run that source

**Comment by xXSirGamesXx** [comment]
But that file works for me.

**Comment by xXSirGamesXx** [comment]
ok finally fixed for real

**Comment by iMOEchan** [comment]
Same here http://i.hizliresim.com/z3ydJO.jpg
