### ISSUE TITLE
Need Devs

### ISSUE THREAD

**Issue by xXSirGamesXx** [FrontierDevs/Genisys3#7]
In order for Genisys3 / FrontierDevs to grow we will need more developers for the organization. Are you a developer or know a developer in PHP/OOP we would like more contributors. If you would like to join comment in this issue.

**Comment by BlawoHD** [comment]
@xXSirGamesXx I am Developer by Bluelight and would like to help you

**Comment by xXSirGamesXx** [comment]
ok ill add you
