### ISSUE TITLE
We need pull request to fix Tesseract stuffs

### ISSUE THREAD

**Issue by Johnmacrocraft** [FrontierDevs/Genisys3#9]
Because we actually started from Tesseract and not Genisys, there are some differences that needs to be changed from Tesseract version to Genisys version. If you find some, please consider making pull request.

**Comment by xXSirGamesXx** [comment]
Actually when I was putting the code together I started from Genisys. I just took 3 of the folders (Blocks, Items, & resources) from Tesserract and implemented them into Genisys.

**Comment by Johnmacrocraft** [comment]
@xXSirGamesXx Really? But language and commands were also Tesseract version.

**Comment by xXSirGamesXx** [comment]
I added a few other files too.

**Comment by Johnmacrocraft** [comment]
@xXSirGamesXx Oh, I didn't know that.

**Comment by Johnmacrocraft** [comment]
Now this issue can be closed because we'll start from repository with 100% Genisys. Currently I'm copying files from this original repository to new repository.
